#!/usr/bin/env perl
use warnings;
use Getopt::Long;

$help      = '';
$beamdir   = "ebin";
$module    = '';
$command   = "killMsg";

GetOptions ('help'    => \$help,
            'beamdir=s' => \$beamdir,
            'module=s'  => \$module,
            'command=s'    => \$command
    ) or usage("ERROR: Invalid option");

if ($help or ($module eq '')) {
  print "usage: pcmd --beamdir=DIRB --module=MODULE --command=CMD\n";
  print "where\n";
  print "DIRB      is a directory where erlang 'beam' files are located (default: ebin)\n";
  print "MODULE    is the name of the module being model-checked (REQUIRED)\n";
  print "CMD       is the message to send all nodes (default: killMsg)\n";
  print "            command=\{killMsg, pauseMsg, resumeMsg, newNode\}\n";
  exit;
}
if ($command eq 'newNode') {
  my $command = "erl -noinput -sname pruserX -rsh ssh -pa $ENV{PWD}/$beamdir -run $module autoLateStart -run init stop -mnesia dir \'\"/tmp/mnesiaX\"\' 2>&1| tee $ENV{PWD}/$module"."X.log &";
  print $command . " \n";
  system($command);
}
else {
  print("erl -noinput -sname usercmd -rsh ssh -pa $ENV{PWD}/$beamdir -run $module $command -run init stop\n");
  system("erl -noinput -sname usercmd -rsh ssh -pa $ENV{PWD}/$beamdir -run $module $command -run init stop");
}
