#!/usr/bin/env perl

open(my $in,  "<",  "hosts")  or die "Can't open hosts: $!";
my @hostsfile = <$in>;
#remove duplicates
undef %saw;
@saw{@hostsfile} = ();
@hosts = keys %saw;
foreach(@hosts) {
    s/\W//;
    print "ssh $_ killall pruser";
    system("ssh $_ killall pruser");
}
close $in or die "$in: $!";
